apiVersion: v1
kind: Service
metadata:
  name: registry-gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP