apiVersion: v1
kind: Service
metadata:
  name: registry-gateway
spec:
  type: NodePort
  selector:
    app: gateway  # Make sure the pods have the correct label
  ports:
    - name: https
      port: 443
      targetPort: 8443
      nodePort: 31437  # Optional: Kubernetes can assign this if omitted
